version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: sequelize
    versions:
    - 6.5.1
    - 6.6.1
  - dependency-name: winston-daily-rotate-file
    versions:
    - 4.5.1
  - dependency-name: swagger-jsdoc
    versions:
    - 6.0.2
    - 6.0.5
    - 6.0.7
    - 6.0.8
    - 6.0.9
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: pm2
    versions:
    - 4.5.2
    - 4.5.5
