name: Build Docker Image
on:
  push:
    branches-ignore:
      - 'master'

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Docker Image Build
      steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v1
        uses: nelonoel/branch-name@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-backend
          tags: ${{BRANCH_NAME}} 
