name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - develop

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Docker Image Build and Run
      steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-backend
          tags: latest
      - name: Clean Up
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker rm --force kuics-backend && docker rmi kuicsofficial/kuics-backend
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
      - name: Generate .env file
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: echo -e "${{secrets.ENV}}" > ~/.env
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
      - name: Run Docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} && docker pull ${{secrets.DOCKER_USERNAME}}/kuics-backend && docker run -d -v /home/ubuntu/log/backend:/kuics-backend/log --env-file ~/.env -p ${{secrets.API_PORT}}:${{secrets.API_PORT}} --name kuics-backend ${{secrets.DOCKER_USERNAME}}/kuics-backend
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
