name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - master

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Docker Image Build and Run
      steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-backend
      - name: Run Docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} && docker run -d -p ${{secrets.API_PORT}}:${{secrets.API_PORT}} --env username=${{secrets.DB_USERNAME}} --env password=${{secrets.DB_PASSWORD}} --env database=${{secrets.DB_DATABASE}} --env host=${{secrets.DB_HOST}} --env dialect=${{secrets.DB_DIALECT}} --name kuics-backend ${{secrets.DOCKER_USERNAME}}/kuics-backend
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
