name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - master

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Build and Push
      steps:
      - name: Show Directory Content
        run: ls -al
