name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - master

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Build and Push
      steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-backend
    run-docker:
      runs-on: ubuntu-latest
      name: Run
      steps:
        - name: Login Docker
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
            host: ${{secrets.SERVER}}
            username: ${{secrets.USERNAME}}
            privateKey: ${{secrets.PRIVATE_KEY}}
        - name: Run Docker Image
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: docker run -d -p ${{secrets.API_PORT}}:${{secrets.API_PORT}} --env username=${{secrets.DB_USERNAME}} --env password=${{secrets.DB_PASSWORD}} --env database=${{secrets.DB_DATABASE}} --env host=${{DB_HOST}} --env dialect=${{DB_DIALECT}} --name kuics-backend ${{secrets.DOCKER_USERNAME}}/kuics-backend
