name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - master

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Build and Push
      steps:
      - name: Show Directory Content
        run: ls -al
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-backend
          tags: latest
